server:
  port: 8001

spring:
  datasource:
    druid:
      stat:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://stack-wr.mysql.rds.aliyuncs.com:3306/txstack?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=CONVERT_TO_NULL
        username: txstack
        password: Stack!@#$
        max-active: 30
        initial-size: 5
        max-wait: 60000
        max-idle: 20
        min-idle: 10
        validation-query: select 1
        test-while-idle: true
        test-on-borrow: true
        test-on-return: false
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
